### ISSUE TITLE
Ability to instrument/uninstrument in UI with ClojureStorm like we do it in Vanilla FlowStorm

### ISSUE THREAD

**Issue by velios** [flow-storm/flow-storm-debugger#114]
First of all thx for great tool. ClojureStorm works faster than vanilla FlowStorm and it's great, but if I use it, I lose the ability to dynamically change the instrumented functions. If I understood correctly from the documentation, then I can only set a template for instrumented namespaces before starting. UI show alert that I can’t change anything in browser tab.  It seems that it would be more convenient if the `-Dclojure.storm.instrumentOnlyPrefixes=` was parsed into the browser tab and allowed to dynamically change the instrumented functions even when ClojureStorm used. Maybe I just don’t know how to use all the functions of the utility and this functionality is already present, I don’t know.

<img width="359" alt="image" src="https://github.com/flow-storm/flow-storm-debugger/assets/9293462/c66b8606-17e5-4108-a2bc-66f71767b200">

**Comment by jpmonettas** [comment]
Thanks @velios! You can currently change what gets instrumented without restarting the repl like this https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_controlling_instrumentation_in_clojurestorm

But I agree that enabling that functionality from the browser is more practical.

**Comment by velios** [comment]
@jpmonettas Thanks for pointing out this functionality. It seems to be quite new or I just didn't notice it when I read the documentation last time. In any case, I'm looking forward to being able to control it through the user interface as well. The way it works in the vanilla version is extremely convenient.

**Comment by jpmonettas** [comment]
@velios The functionality isn't new but it wasn't documented for a long time. I'll experiment with doing this from the UI when I get some time.

**Comment by jpmonettas** [comment]
This is now implemented after 1284243
