### ISSUE TITLE
Navigation in test body

### ISSUE THREAD

**Issue by velios** [flow-storm/flow-storm-debugger#120]
Quite often I start studying a project with tests and really lack some tools for navigating the body of the test. I mean deftest and testing sections. I try workaround with add deftest and testing to prints, but it's point to specific test and i can't get all testing sections as list.

In tree view test shows as <ns>/fn--<num> and not easy to find where test begins without moving back and forth through the code.

Maybe i just not find proposed method to solve this

**Comment by jpmonettas** [comment]
Hi! @velios I'm not sure I follow. You should be able to step over your tests bodies the same as any function.
It is true that currently the tests shows as anonymous functions which can probably be fixed, I'll create a issue for this.

If I create this test :
```clojure
(deftest adding-test
  (testing "Addition"
    (is (= 10
           (+ 1 2 3 4)))))
```

and run it, on the tree I see : 

![latest-screenshot](https://github.com/flow-storm/flow-storm-debugger/assets/786299/e449acbc-e28f-4f38-a8e1-c0308ba84d8b)

so I can see which test it is about, while on the code stepper I can step over the expressions : 

![latest-screenshot](https://github.com/flow-storm/flow-storm-debugger/assets/786299/2baaf1d7-eceb-4f45-a04c-30b686fa6ed8)

Is that not how it behaves on your system?

**Comment by velios** [comment]
It behaves as you described, I can navigate through the test blocks and no problem with that. The only problem is that these blocks have special meaning(test block start) for me and I would like some more convenient mechanism to navigate to them. The gray part on the right is sometimes missing and in such cases the task of finding the beginning of the test becomes much more difficult.

**Comment by jpmonettas** [comment]
>The only problem is that these blocks have special meaning(test block start) for me and I would like some more convenient mechanism to navigate to them

I'm not sure I follow that part. Can you maybe paste some code examples or some screenshot?

**Comment by velios** [comment]
<img width="689" alt="image" src="https://github.com/flow-storm/flow-storm-debugger/assets/9293462/cfd1a445-706e-40c4-bd96-fa1b4da3df51">

Of course, arrows point to deftest sections. And i don't have pointers to (testing... ) sections at all. 

<img width="639" alt="image" src="https://github.com/flow-storm/flow-storm-debugger/assets/9293462/961a2a76-1d06-4e04-8b55-1ca3ea415d33">

I think it would be handy to have some type of highlighting for these structures.

**Comment by jpmonettas** [comment]
Interesting, so when you run with your test runner then you just see the test runner form.
I created this issue https://github.com/flow-storm/flow-storm-debugger/issues/121 to track `deftest` functions showing as anonymous  fns, which I guess should help a lot.

**Comment by velios** [comment]
Yes, it definitely helps. Also i look at testing inners. It contains something special *testing-contexts* thing and it's seems reasonable why we don't see track.

```
(defmacro testing
  "Adds a new string to the list of testing contexts.  May be nested,
  but must occur inside a test function (deftest)."
  {:added "1.1"}
  [string & body]
  `(binding [*testing-contexts* (conj *testing-contexts* ~string)]
     ~@body))
```

Perhaps some kind of color indication of changing the test context in tree view would also simplify navigation in the tests.

**Comment by jpmonettas** [comment]
Currently ClojureStorm/FlowStorm only instrument things that the user can see, which means we are tracing user's code. The way it works for macros is it will tag everything before macroexpansion, then macro-expand the form and instrument only the things that were tagged.

What is your idea on tracing for example the value of *testing-contexts*, how would you show that to the user who don't know that even exists?

**Comment by velios** [comment]
I think this cannot be done without adding crutches specifically for this special case.

Theoretically. We can start tracking the test context when we see that we are inside the deftest in special binding. And then assign a meta for the step, when testing context is changing. But I believe it's bad and confusing solution, because it adds non-obvious additional layer.

I think if #121 will be done it's more than enough simplify the task of finding where the test begins. During the test run, i sure user can also comment out all unnecessary `testing` blocks if it worries about noise in the tracked data.

**Comment by jpmonettas** [comment]
Yeah I agree that will be extra non-obvious code for not a lot of benefit.
Fixing #121 should improve the situation a lot, because you can then use the quickbox to jump right into the test you are interested in or the functions list to see all the tests and jump to them.
