### ISSUE TITLE
Show frame id in the bookmark list

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#122]
It would be nice to see a frame id in the bookmark list to quickly understand what parts of the timeline bookmarks represent.

**Comment by jpmonettas** [comment]
What do you mean by a frame id? Also you can put any text on your bookmark so you can also describe there what function is inside. You can copy the current fn name to the clip board by hitting Ctrl+F

**Comment by mrkam2** [comment]
That's the number of the frame in the timeline.

**Comment by jpmonettas** [comment]
Oh ok, yeah, I call it the timeline index. I call frame to  the function frame, which are all the entries inside a function call. That make sense. I'll add it.
