### ISSUE TITLE
Show frame number in the multi-threaded timeline

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#123]
It would be great to see frame ids of different actions in the multi-threaded timeline. Otherwise it is hard to understand how different threads intervene.

**Comment by mrkam2** [comment]
I'm referring the number of the frame in the individual thread timeline.

**Comment by mrkam2** [comment]
But yes, overall the idea is to have it as a column in the table.

**Comment by jpmonettas** [comment]
Yeah, now it make sense, that should be pretty easy to add.
