### ISSUE TITLE
Allow to search an object between threads.

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#127]
There is a very useful UI to follow an object in a timeline. 
![image](https://github.com/flow-storm/flow-storm-debugger/assets/28267638/5cabc99e-5f10-4430-b194-6db13dc16e19)

For multi-threaded apps it would be super useful to do the same among all threads.

Slack: https://clojurians.slack.com/archives/C03KZ3XT0CF/p1706029582998599.

**Comment by jpmonettas** [comment]
I think it is an interesting concept to explore. Do you have any ideas already on UI/UX for a feature like this?

**Comment by jpmonettas** [comment]
One issue I see with this is that currently we don't have a total order between threads unless the multi-thread timeline is enable, which it isn't by default because of perf reasons.

Maybe we can enable this feature when a multi-thread timeline is enable and available?
