### ISSUE TITLE
Allow to jump to any line in the source code

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#129]
When having a source code open, allow jumping to any point in time associated with a particular line.
For example, when I'm looking at a source file that has not purple or green highlights, I should be able to click on any line and be given a choice of timestamps associated with this line to quickly get into this line debugging.

Slack: https://clojurians.slack.com/archives/C03KZ3XT0CF/p1706051437525539

**Comment by velios** [comment]
Sounds similar to the [functionality](https://www.jetbrains.com/idea/whatsnew/2023-3/img/Run_to_cursor.gif) that recently appeared in the IntellijIDEA. 
Run to Cursor inlay option in the debugger on [whatsnew](https://www.jetbrains.com/idea/whatsnew/) page.
Maybe this will be useful as an example of UI.

**Comment by jpmonettas** [comment]
This has been implemented in a dev branch, still a WIP but works, you can try it with :

```clojure
{com.github.flow-storm/clojure {:mvn/version "1.11.1-18"}
 com.github.flow-storm/flow-storm-dbg {:git/url "https://github.com/flow-storm/flow-storm-debugger" :git/sha "5b16df5715134863049948e20bead12e5fda9324"}}
```
You can right click on any un-highlighted form and then click on `Jump to first record here`

**Comment by jpmonettas** [comment]
This is now on master

**Comment by mrkam2** [comment]
Awesome!
