### ISSUE TITLE
Allow to evaluate an expression in printer

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#130]
It would be great if I was possible to evaluate and print a custom expression using the data available in a printer position. So the following two scenarios are possible:

- Evaluate an expression over several values in a given point of the code. Such as `(+ a b)`.
- Modify the expression returned by a given form. For example, `(select-keys % [:a :b])`.

Slack: https://clojurians.slack.com/archives/C03KZ3XT0CF/p1706144050247019

**Comment by jpmonettas** [comment]
I think this is a nice thing to have.

> Evaluate an expression over several values in a given point of the code. Such as (+ a b).
this is tricky to implement if possible at all.

> Modify the expression returned by a given form. For example, (select-keys % [:a :b])
this one is imo the way to go

**Comment by jpmonettas** [comment]
This is currently on master, checkout  https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_printer_tool

**Comment by mrkam2** [comment]
> This is currently on master, checkout https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_printer_tool

This is awesome! Thank you for adding!
