### ISSUE TITLE
Pasting into Quick jump doesn't open search results

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#133]
When I paste a function name into the Quick jump field, the list doesn't appear. If I edit it or type in manually, the function gets shown in the list.

**Comment by jpmonettas** [comment]
Interesting

**Comment by mrkam2** [comment]
Yeah, its a bit more than that. Often times the list doesn't populate even if I edit it. Could it be that the lookup fails in some cases?

**Comment by mrkam2** [comment]
I can try to do a screen cast if that's helpful.

**Comment by jpmonettas** [comment]
Don't worry, I was able to reproduce it.
