### ISSUE TITLE
Highlight the current line

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#140]
Add a contrast background for the current line as finding as single green `(` symbol in a big portion of code is hard.

Slack: https://clojurians.slack.com/archives/C03KZ3XT0CF/p1706555397347279?thread_ts=1706384332.443059&cid=C03KZ3XT0CF

**Comment by jpmonettas** [comment]
Now it looks like this ; 

![latest-screenshot](https://github.com/flow-storm/flow-storm-debugger/assets/786299/dd5ad345-1c8c-434c-9b48-247be28358d5)

**Comment by mrkam2** [comment]
Awesome! Thanks!

Best regards,
Alexander
