### ISSUE TITLE
It's not clear to users they have to double-click on fn list items to show their args

### ISSUE THREAD

**Issue by maxrothman** [flow-storm/flow-storm-debugger#145]
In the function list view, seeing the list of all a function's call args requires double-clicking because generating that list is a slow operation. Making that operation cancellable and adding a progress indicator is covered by #143, but it's still unclear to users that double-clicking is necessary to trigger it, because in the rest of the UI, list items only need a single click to trigger. To improve this UX, there needs to be some affordance to prompt the user to trigger the operation.

One option would be to have a button that appears on hover that the user could click to trigger the operation. For example:
![ScreenRecording2024-02-13at11 07 52AM-ezgif com-video-to-gif-converter](https://github.com/flow-storm/flow-storm-debugger/assets/2607086/1cfdec03-bddc-4304-ac14-5ff5e0fdbf73)

The button text could be something like "View", "Show", "Focus", "Show calls", etc.

The operation should also be triggered when the user focuses an item and presses enter.

This approach is definitely a little "web-y", there might be approaches that are better suited for a native app look-and-feel. The important thing is that the action required is obvious to the user.

**Comment by maxrothman** [comment]
It must be my birthday, because all my issues got closed today! I worry a little that though we have a button now, there's no "call to action", nothing tells the user what will happen when they click it. I still think having a separate button column would be better, but this is still better if that's technically challenging.

**Comment by jpmonettas** [comment]
My idea was that since they look like buttons, and highlight like buttons, it should lead the user to click them. 
The hover buttons thing you proposed, while normal on the web I think is pretty rare on desktop apps, and I didn't want to add another column that will contain action buttons if we can make the `calls counter` a button. 

Maybe we can add a tooltip?

Still open to improvements here.

**Comment by maxrothman** [comment]
Yeah, totally understand the desire to not add another button. Unfortunately, I think that the number buttons don't read strongly to users as "buttons". I did a little more thinking about this and posted my thoughts in #147
