### ISSUE TITLE
After navigating away from and back to the fn list view, you can no longer tell what data you're viewing

### ISSUE THREAD

**Issue by maxrothman** [flow-storm/flow-storm-debugger#147]
In the function list view, the data in the right-hand panes is showing detail of the selection in the left-hand pane. Consider the following steps:
- User goes to the fn list and selects a fn they want to see calls for
- User finds the call they're looking for and double-clicks it to go to the code stepper
- User returns to the fn list to inspect a different call

When the user returns to the fn list, the list selections in all panes are cleared, so they can no longer tell which fn they're seeing args for, or which args they're seeing return values for. Instead, the selection state should be persisted, so that after leaving and returning to the fn list, the lists still have the same items selected.

**Comment by jpmonettas** [comment]
![latest-screenshot](https://github.com/flow-storm/flow-storm-debugger/assets/786299/117a9506-dc63-40d9-af26-69988b5df152)

Now it has a label on top of the calls showing what functions the calls are for.

**Comment by maxrothman** [comment]
Thanks for working on this! Though this is definitely an improvement, it's not scan-able in the way that keeping the selection highlight would be. I take it there's some technical limitation making it difficult to keep the selection highlighted between view loads?

**Comment by jpmonettas** [comment]
Currently in my box it keeps the selection when you move around other tabs. One small issue I see is if you use the new buttons it doesn't select the row, but I think that should be easy to fix.

**Comment by maxrothman** [comment]
Spent some more time thinking about this, a few thoughts:

Having buttons is definitely an improvement over the user just having to know to double-click, but having the button text show the number of calls doesn't strongly signal to the user that the button is clickable. Given that this could be revisited once that loading pattern is in place, I think it's worth picking a somewhat uglier but more clear approach in the short term. I'd suggest having a separate column containing a button for each row that has some text that strongly signals clickability, like "show detail" or "show" or "focus", etc. It's not the most pretty solution, but once the loading pattern is in place the buttons could be removed and detail focus could just follow list selection.

This also puts focus on another thing: since list selection is decoupled from what's shown in the detail box, looking at what's selected doesn't necessarily tell you what's being shown in the detail box. Consider this sequence:
- User shows detail on item A
- User selects (but does not click the button) on another list item
- User navigates away from the view, then returns to it

Now the user has no way of knowing what's being shown in the detail box.

Here's my suggested approach:
- Remove the ability to select items in the list. It doesn't actually do anything right now, and it can be added back if/when there's a loading pattern and detail view follows list selection. Having items be selectable is just confusing at the moment.
- Indicate the item currently shown in the detail view by changing the background color of the row. I wouldn't use a blue for this since that could be confused with selection, but a teal or bluish green could work. As long as it's possible to read the row text and it doesn't look like "selection blue", anything is fine.

On the bright side, now there's no need to  maintain list selection across navigation because there's no selection at all! 🤪

**Comment by jpmonettas** [comment]
Yeah, this still needs improvements but there are a couple of issues.

> Now the user has no way of knowing what's being shown in the detail box.

I agree that is not the best option but there is a label at the top that always shows what is currently being displayed
  
> Remove the ability to select items in the list

wouldn't this remove the current ability to use that list with the keyboard?

Now we have interruptible tasks we could try the auto update on list selection, but I'm still not sure. To improve perf we are allowing interruption on batch edges, so even if tasks are interruptible, the could take a little bit, which will render keyboard navigation unusable.
