### ISSUE TITLE
Font size setting (to increase font size)

### ISSUE THREAD

**Issue by DanEEStar** [flow-storm/flow-storm-debugger#15]
I discovered the tool today and it's great!

The font is a bit too small for my taste right now?
Is it possible to increase the font size?

**Comment by jpmonettas** [comment]
Hey, glad you find the tool useful. 

I just released version 0.3.4 which includes style customization, so you can use that to increase font size, change colors etc.

Check https://github.com/jpmonettas/flow-storm-debugger#customizing-styles.

I hope that helps!
Cheers.

**Comment by DanEEStar** [comment]
Thank very much you. It works!

The only thing that confused me at the beginning was, that the `--spit-style-files` option will not open the application, and that I have to open the application without the option to make it open the GUI.

**Comment by jpmonettas** [comment]
Great! I'll add to the documentation and try to make that less confusing.

**Comment by jpmonettas** [comment]
Ok, version `3.8.3` now supports dynamic font sizes with `Ctrl-+` and `Ctrl--` and also dynamic theme rotation with `Ctrl-t`.

Font sizes will increase/decrease over 4 pre-settings sm->md->lg->xl

**Comment by agzam** [comment]
I'm sorry for being a nuisance here, I just tried font resizing. It's great, thank you very much! However, on a Mac it should probably respond to `Cmd+/-` rather than `Ctrl-+`. I personally don't care how it's done, but perhaps sticking to the OS idioms would make the feature more discoverable and save you from having to add a bullet point to Q&A in documentation.

**Comment by jpmonettas** [comment]
That shouldn't be hard, it should be to add a or clause here https://github.com/flow-storm/flow-storm-debugger/blob/master/src-dbg/flow_storm/debugger/ui/main.clj#L371-L380

The problem is that I don't have a way to test it, since I don't own a mac

**Comment by agzam** [comment]
Great, I'll try to file a PR when I get a chance. It may take a while though since I am currently swamped with work-related things. Thank you @jpmonettas!
