### ISSUE TITLE
Make Stack double-click and Step Out go to the step that is relative to the current position in timeline

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#150]
As discussed in [slack](https://clojurians.slack.com/archives/C03KZ3XT0CF/p1708107736150259), the expectation from the Stack double-click and Step Out actions are to go to the last step before entering the function and first step after exiting the function respectively. So that step forward after Stack double-click steps into the function that were above in the clicked line on the Stack. And step back after Step Out steps into the function we were in before Stepping Out.

**Comment by mrkam2** [comment]
Awesome! Is there a release already containing this fix?

Best regards,
Alexander

**Comment by jpmonettas** [comment]
Not yet, but you can use it from master with :git/url and :sha
