### ISSUE TITLE
"No matching clause" exception while going through tutorial

### ISSUE THREAD

**Issue by erno** [flow-storm/flow-storm-debugger#154]
Wiith 1.12.0-alpha4_14 + jdk 17, in the tutorial phase starting with "The `functions list tool` shows you all the functions next to how many times they have been called." .. I got a stack trace which is attached. the topmost line is components.clj:90

It seems to reproduce when I select the factorial fn in function lists, and double click an arg so that it switches to the call tree tab, and switch back to the function lits tool and double click a function to select it.

[stacktrace.txt](https://github.com/flow-storm/flow-storm-debugger/files/14478651/stacktrace.txt)

**Comment by jpmonettas** [comment]
Thanks for reporting! This seems to be fixed in the current master version which I'm going to release soon. But just figured that the tutorial is outdated on the functions calls tool and the exception navigation system, so I'll update that too.
Will close this after the fix is released.

**Comment by jpmonettas** [comment]
This has been fixed in `3.12.2`
