### ISSUE TITLE
Steps missings / mixed up in ClojureScriptStorm

### ISSUE THREAD

**Issue by lidorcg** [flow-storm/flow-storm-debugger#155]
Hello,

I'm using:
```clojure
{com.github.flow-storm/flow-storm-inst {:mvn/version "3.12.2"}
 com.github.flow-storm/clojurescript {:mvn/version "1.11.132-1"}}
```

And I'm experiencing some bugs on the code tool:

Here is example of some step appearing in the wrong place:

There's no return step for `olookup`:
![Screenshot from 2024-03-11 16-34-46](https://github.com/flow-storm/flow-storm-debugger/assets/11412645/5d52c7bd-75cf-4bd8-8e28-e6f16d54f8eb)

And here's the step sequence:

![Screenshot from 2024-03-11 16-45-59](https://github.com/flow-storm/flow-storm-debugger/assets/11412645/59de7cf2-2174-40b0-8302-c9231614043e)
![Screenshot from 2024-03-11 16-46-04](https://github.com/flow-storm/flow-storm-debugger/assets/11412645/080f8ee3-3c65-44ec-8ade-0f806cd8a455)

Notice the next step takes us back to `ocontains` but shows the return value from `olookup`
![Screenshot from 2024-03-11 16-46-23](https://github.com/flow-storm/flow-storm-debugger/assets/11412645/08205296-0ce0-4fee-80d3-a0d590487f60)

**Comment by jpmonettas** [comment]
The only way I could reproduce this situation is by making `olookup` throw (possible from your screenshots), then it make sense that you don't have a return value, but if you are using the latest version of the debugger it should work fine and you should see the exceptions, like the in the picture below.

![clojurescript-repro](https://github.com/flow-storm/flow-storm-debugger/assets/786299/304e5000-45d8-40d1-9c33-85548097edbc)

 What version of the FlowStorm debugger are you running with? Maybe you only updated flow-storm-inst but are running with an older debugger?

**Comment by jpmonettas** [comment]
Can you try to reproduce it?

**Comment by lidorcg** [comment]
Well, it's quite funny:
I encounter this behavior when I'm dealing with a bug on a large prod system that slipped the test suite.
Trying to reproduce in a smaller context is the name of the game for me 😂

If I'll come up with something I'll let you know 🙂

**Comment by jpmonettas** [comment]
I'm closing this for now @lidorcg , please re-open if you experience this again.
