### ISSUE TITLE
Ability to run flowstorm from a global profile

### ISSUE THREAD

**Issue by rafd** [flow-storm/flow-storm-debugger#156]
Following up [on our discussion on Clojurians Slack](https://clojurians.slack.com/archives/C03KZ3XT0CF/p1709359476240569).

It would be really nice if it were possible to configure flow-storm from a global lein profile or a global deps profile, so that a developer would only need to set those profiles once (with sensible defaults), rather than per project. 

I have 30+ Clojure projects, and having to configure flow-storm for each is more friction than I'm willing to go through. But, since I made a global lein profile, I've been using flow-storm as a default for most projects ("need to debug, oh, just restart repl with flowstorm enabled").

I added the following to my global lein profile (`~/.lein/profiles.clj`):
```clojure
{:flowstorm
            {:dependencies [[com.github.flow-storm/clojure "RELEASE"]
                            [com.github.flow-storm/flow-storm-dbg "RELEASE"]]
             :repl-options {:init (do (require '[flow-storm.api :as fs-api])
                                      (fs-api/local-connect))}
             :exclusions [org.clojure/clojure] ;; for disabling the official compiler
             :jvm-opts ["-Dclojure.storm.instrumentEnable=true"
                        #=(eval (str "-Dclojure.storm.instrumentOnlyPrefixes="
                                     (->> (.listFiles (java.io.File. "src"))
                                          (filter #(.isDirectory %))
                                          (map #(.getName %))
                                          (map #(str % "."))
                                          (interpose ",")
                                          (apply str))))]}}
```
In any lein project, when I run `lein with-profiles +flowstorm repl`, the repl is started and flow-storm is immediately started, with everything under `src` instrumented.

Perhaps we could add a function to [flow-storm/api](https://github.com/flow-storm/flow-storm-debugger/blob/master/src-inst/flow_storm/api.clj) to default to instrumenting whatever is in `:source-paths` (not just `\src`). 

Then, the instructions for getting started might change to:

 ----

  Add the following to your ~/clojure/deps.edn:
  ```clojure
   {:aliases
   {:flowstorm
    {:classpath-overrides {org.clojure/clojure nil}
     :extra-deps {com.github.flow-storm/clojure {:mvn/version "RELEASE"}
                  com.github.flow-storm/flow-storm-dbg {:mvn/version "RELEASE"}}
     :jvm-opts ["-Dclojure.storm.instrumentEnable=true"]
     :exec-fn clojure.core/instrument-source-paths-and-local-connect}}}     ;; <-- this needs to added
  ```
  Runnable as: `clj -X:flowstorm`
  
  Add the following to your ~/.lein/profiles.clj
  ```clojure
  {:flowstorm
              {:dependencies [[com.github.flow-storm/clojure "RELEASE"]
                              [com.github.flow-storm/flow-storm-dbg "RELEASE"]]
               :exclusions [org.clojure/clojure]
               :repl-options {:init (do (require '[flow-storm.api :as fs-api])
                                        (fs-api/instrument-source-paths-and-local-connect))}    ;; <-- this would be nicer than my hack above
               :jvm-opts ["-Dclojure.storm.instrumentEnable=true"]}}
  ```
  Runnable as: `lein with-profiles +flowstorm repl`

---

**Comment by jpmonettas** [comment]
What about adding to ClojureStorm something like `-Dclojure.storm.instrument.autoPrefixes=true` which runs something like this : 

```clojure
(defn root-ns-prefixes []  
  (let [source-directories (->> (str/split (System/getProperty "java.class.path") #":")
                               (keep (fn [path]
                                       (let [f (java.io.File. path)]
                                         (when (and (.isDirectory f)
                                                    (not= path "resources"))
                                           f)))))]
    (->> source-directories
         (map (fn [f]
                (->> (.listFiles f)
                     (filter #(.isDirectory %))
                     (map #(.getName %))
                     (map #(str % "."))
                     (str/join ","))))
         (into #{})
         (str/join ","))))
```

to determine the prefixes automatically?

**Comment by rafd** [comment]
Two minor changes (see comments in code below):

```clojure
(defn root-ns-prefixes []  
  (let [source-directories (->> (.split (System/getProperty "java.class.path")
                                        (System/getProperty "path.separator")) 
                                ;; (1) ^ use path.seperator, as per:
                                ;; https://github.com/clojure/java.classpath/blob/master/src/main/clojure/clojure/java/classpath.clj#L62
                                (keep (fn [path]
                                        (let [f (java.io.File. path)]
                                          (when (and (.isDirectory f)
                                                  ;; (2) use .getName and ignore target/classes too
                                                  (not (#{"resources" "classes"} (.getName f))))
                                            f)))))]
    (->> source-directories
         (map (fn [f]
                (->> (.listFiles f)
                     (filter #(.isDirectory %))
                     (map #(.getName %))
                     (map #(str % "."))
                     (str/join ","))))
         (into #{})
         (str/join ","))))
```

Optionally, some refactoring and use of `mapcat` to remove nils in final output when there is an empty directory in classpath:

```clojure
(defn root-ns-prefixes []
  (->> (.split (System/getProperty "java.class.path")
               (System/getProperty "path.separator"))
       (map #(java.io.File. ^String %))
       (filter (memfn ^java.io.File isDirectory))
       (remove #(#{"resources" "classes"} (.getName ^java.io.File %)))
       (mapcat (memfn ^java.io.File listFiles))
       (filter (memfn ^java.io.File isDirectory))
       (map (memfn ^java.io.File getName))
       (map #(str % "."))
       (into #{})
       (str/join ",")))
```

The only other thing to consider, is whether to provide a function in flowstorm-api to allow launching the GUI directly after REPL start in `deps.edn`. I'm figuring out if `:exec-fn` can be used for this.

**Comment by rafd** [comment]
Or potentially a `-Dclojure.storm.local_connect_immediately=true` that triggers:
```
(do (require '[flow-storm.api :as fs-api])
                                      (fs-api/local-connect))
```

**Comment by rafd** [comment]
With the above two changes, the doc change could be:

**For deps projects:**

Add the following to your `~/clojure/deps.edn`:
```clojure
 {:aliases
 {:flowstorm
  {:classpath-overrides {org.clojure/clojure nil}
   :extra-deps {com.github.flow-storm/clojure {:mvn/version "RELEASE"}
                        com.github.flow-storm/flow-storm-dbg {:mvn/version "RELEASE"}}
   :jvm-opts ["-Dclojure.storm.instrumentEnable=true"
              "-Dclojure.storm.instrument.autoPrefixes=true"
              "-Dclojure.storm.localConnectImmediately=true"]}}} 
   ```
Runnable as: `clj -A:flowstorm`

**For lein projects:**

Add the following to your `~/.lein/profiles.clj`
```clojure
{:flowstorm
            {:dependencies [[com.github.flow-storm/clojure "RELEASE"]
                            [com.github.flow-storm/flow-storm-dbg "RELEASE"]]
             :exclusions [org.clojure/clojure]
             :jvm-opts ["-Dclojure.storm.instrumentEnable=true"
                        "-Dclojure.storm.instrument.autoPrefixes=true"
                        "-Dclojure.storm.localConnectImmediately=true"]}}
```
Runnable as: `lein with-profiles +flowstorm repl`

**Comment by rafd** [comment]
Once you're happy with the plan, I'd be happy to make a PR.

**Comment by jpmonettas** [comment]
Yeah I agree with the suggestions, my original code was just a sketch since both of those options (instrument.autoPrefixes and  localConnectImmediately) and root-ns-prefixes code belongs to ClojureStorm instead of FlowStorm and would have to be probably written in Java as the rest of the prefixes code, [here](https://github.com/flow-storm/clojure/blob/clojure-storm-master/src/jvm/clojure/storm/Emitter.java#L65-L86) 

FlowStorm doesn't deal with anything instrumentation related, it is just about recording and exploring stuff that something else instrumented (Clojure[Script]Storm and Clojure[Script]Hansel for vanilla).

Does it make sense?

**Comment by jpmonettas** [comment]
> Or potentially a `-Dclojure.storm.localConnectImmediately=true` that triggers:
> 
> ```
> 
> ```

This I'm not sure it worth a property since running the debugger is a matter of typing `:dbg` on any repl. Which takes less than a second and easy to remember.
Also having that globally would make your repls slower to start for the cases which you don't need the UI loaded.

**Comment by jpmonettas** [comment]
@rafd  I gave this a shot and I think it looks promising.

It is on `clojure-storm-master`, I'll release it after you confirm it works fine for your situation.

For trying it you can clone https://github.com/flow-storm/clojure the `clojure-storm-master` branch which is the default and then `make install`. That should build and install in your local .m2 a `com.github.flow-storm/clojure 1.12.0-SNAPSHOT`.

Using that you can then configure your globals with `"-Dclojure.storm.instrumentAutoPrefixes=true"` and it should figure out prefixes for you.

You can check the prefixes by evaluating `:help`, they will show at the top.

**Comment by rafd** [comment]
Cool. There is no `Makefile` in the clojure project, only this one. Should I be running `ant`?

**Comment by jpmonettas** [comment]
@rafd Dang, I forgot to commit the make file. It is there now. It is just `mvn -Dmaven.test.skip=true clean package install`

**Comment by rafd** [comment]
Tried it. Works. It's picking up on `/resources/public`, but that's fine for me. I guess if someone has `/resources/clojure` it may end up instrumenting `clojure.core`?

I didn't know about `:dbg` ... I agree, that's convenient enough.

**Comment by jpmonettas** [comment]
>  It's picking up on /resources/public

It should be grabbing every folder on the classpath which contains a clj or cljc file inside, and from those folders take the immediate childs as prefixes. 

>  I guess if someone has /resources/clojure it may end up instrumenting clojure.core

You can still use `-Dclojure.storm.instrumentSkipPrefixes` and `-Dclojure.storm.instrumentSkipRegex` to skip a subset of auto prefixes as documented here https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_controlling_instrumentation if that is the case.

I'm closing this now, please re-open if you feel something else needs to be done.
