### ISSUE TITLE
Split open form command by whitespace

### ISSUE THREAD

**Issue by alexmalcoci** [flow-storm/flow-storm-debugger#162]
Currently the command that opens a form in editor is split by a space character `" "` [here](https://github.com/flow-storm/flow-storm-debugger/blob/a98857ca6f6e2fdd05003881646705b37ca23b9f/src-dbg/flow_storm/debugger/ui/flows/general.clj#L95). Trying to integrate flowstorm with cursive, I was unable to set the `-Dflowstorm.fileEditorCommand` JVM arg, because it splits the command at spaces, even if the command is quoted, which crashes the run. One way I thought about to work around it  was to split the command using other whitespace char, like newline `idea\n--line\n<<LINE>>\n<<FILE>>`, which cursive does accept. In order to make it work, I need flowstorm to split the command by the whitespace regex pattern `\s` before passing it to `clojure.java.shell/sh`, which handles both regular spaces and other whitespace chars.

**Comment by jpmonettas** [comment]
Hi! I'm curious about this. I just tried it on linux and it opens fine in intellij. 

What system are you in and what command are you trying?

I just tried this and it works : 

```
"-Dflowstorm.fileEditorCommand=/home/jmonetta/non-rep-software/idea-IC-223.8214.52/bin/idea.sh --line <<LINE>> <<FILE>>"
```

**Comment by alexmalcoci** [comment]
I'm on a mac (Sonoma 14.3.1). The error happens if I try to set the JVM arg in intellij run configuration (so maybe that's an intellij issue, not cursive). 

This is what happens if I quote the entire arg
![image](https://github.com/flow-storm/flow-storm-debugger/assets/34559371/7a03aedc-20d3-48f9-9ad2-f733fed6bff9)
```
Error: Could not find or load main class "-Dflowstorm.fileEditorCommand=idea
Caused by: java.lang.ClassNotFoundException: "-Dflowstorm.fileEditorCommand=idea
```

And if I only quote the value
![image](https://github.com/flow-storm/flow-storm-debugger/assets/34559371/7fab13df-4b99-40cb-afe1-f992fb315c75)
```
Unrecognized option: --line
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by jpmonettas** [comment]
Oh interesting. I thought you were adding those to your deps.edn.
And how are you suppose to pass properties which contains spaces, like when you need to provide folders?

Anyway, great you came up with this solution if that works
