### ISSUE TITLE
Add go to specific line feature

### ISSUE THREAD

**Issue by mrkam2** [flow-storm/flow-storm-debugger#168]
One common way of navigating the source code is by jumping to a specific line in a file. Would've been great to have a popup, where you type a file name or a namespace name and a line number in it and the UI would jump to that. Something `my-company.my-namespace:123` or `my_company/my_namespace.clj:123`. I'm specifically giving the example containing dots, dashes, underscores and slashes to remind about what particular annoying this that you may only have one form and the UI may only accept another and you have to manually edit it. Ideally this should accept both. We can also consider adding a jump from the currently selected line in editor as an alternative.

Discussion link: https://clojurians.slack.com/archives/C03KZ3XT0CF/p1711124000385799?thread_ts=1711119029.324069&cid=C03KZ3XT0CF.

**Comment by jpmonettas** [comment]
Isn't the `Quick Jump` + `Jump to first record here` much faster than a window to type or copy->paste->format a filename and a line?
I can see this being handy as an editor integration, so a keystroke on the editor can take you there faster, and we could add it in the nrepl middleware, but then it would require specific editors plugins or setups to be useful.

**Comment by mrkam2** [comment]
> Isn't the `Quick Jump` + `Jump to first record here` much faster than a window to type or copy->paste->format a filename and a line? I can see this being handy as an editor integration, so a keystroke on the editor can take you there faster, and we could add it in the nrepl middleware, but then it would require specific editors plugins or setups to be useful.

Quick jump is a great tool. So maybe this could be combined. Like that you can paste the string with the line number to jump to that line precisely. Without this I still need to manually search through the code to find something that I already have opened in my editor. And I'm also looking for a particular line of code, rather than the beginning of the test or a function which may be many lines and screens away.

Since we're talking about Quick Jump, we could also improve it:
- by not showing all the anonymous functions. Those are usually concatenations of different names and numbers and most of the time you don't know which one you're looking for. I often do not see the main function that contains them because there is so many of them.
- by prioritizing exact matches or supporting regexp. It is quite often that the name of the function of interest is a substring of another function or namespace name and all of those gets shown (with all of those anonymous functions). So it may be tricky to find what you're looking for when it may not even fit in the list due to list size limit and a lot of matches.

**Comment by mrkam2** [comment]
> I can see this being handy as an editor integration, so a keystroke on the editor can take you there faster, and we could add it in the nrepl middleware, but then it would require specific editors plugins or setups to be useful.

Yeah, editor integration would be the best. But that requires some setup which users may not have. So it is good to have a simple alternative.

**Comment by jpmonettas** [comment]
> by not showing all the anonymous functions.

Yeah, we could remove all the fn--DIGIT named ones, but leave the named ones, like `(fn named [] )`

> by prioritizing exact matches or supporting regexp

I guess it also make sense

**Comment by jpmonettas** [comment]
@mrkam2 There are a couple of commits now on master that implements `Action->Goto flie:line` and the Quick Jump autocomplete doesn't show unnamed anonymous functions.

**Comment by mrkam2** [comment]
Nice! I'll give it a try.
