### ISSUE TITLE
Why is the project not applied for funding through clojuriststogether?

### ISSUE THREAD

**Issue by velios** [flow-storm/flow-storm-debugger#172]
Flowstorm project is truly wonderful and important to the community, but I have never seen it voted for support on https://www.clojuriststogether.org/. This is just curiosity, but I wanted to know why it is not there, although flowstorm is actively developing and seems to meet all the [criteria for funding](https://www.clojuriststogether.org/open-source/).I thought about adding flowstorm myself, but if I read the rules correctly, only the owner of the project repository can do this.

**Comment by jpmonettas** [comment]
Hi @velios, I don't know how to answer that tbh. I added it twice already and never got  accepted 🤷🏼‍♂️

**Comment by velios** [comment]
Thank you for the clarification, @jpmonettas . For me, flowstorm is masterpiece and my everyday partner, which made with brilliant ideas and attention to detail. Оne of the reasons to continue development in clojure. I was sure that if a project of this quality could not be accepted if it was submitted. Apparently I was wrong. I apologize if I accidentally raised an awkward question.

**Comment by jpmonettas** [comment]
Hey thanks for the feedback and this is not awkward at all, I have also wonder why that was the case that it wasn't being accepted, but it seems people voted for other projects, so it is what it is.

**Comment by velios** [comment]
If the process is not very tedious, then you will try again next time. Who knows, maybe the time has come. =)

**Comment by jpmonettas** [comment]
Yeah, will try it again, it is not tedious at all.

**Comment by velios** [comment]
@jpmonettas  Sorry for bothering you, I am still, as always, confident that your project is the best tooling for development that the clojure community has. So just wondering if you plan on applying to [Applications Open for 2025 Long-Term Funding](https://www.clojuriststogether.org/news/applications-open-for-2025-long-term-funding/)? I can't do it myself unfortunately only authors can apply if I understood the terms correctly.

**Comment by jpmonettas** [comment]
@velios Thanks for the kind words. I applied recently (a couple of months ago) again for the third time, and wasn't selected, so not sure.

**Comment by velios** [comment]
@jpmonettas Yes, I can understand, rejections are demotivating. But I still believe that your project is more worthy of this funding than any other. For me, Flowstorm opened a whole new dimension, allowed me to look at my own code from a different angle and travel back and forth through it. Without Flowstorm, I would never have felt such unity with my code. They write that they have a new system for selecting projects. Whoever they choose for me, Flowstorm was and will remain one of the most useful in practice, and its code, documentation and your support are the best I have ever seen in my entire life.

**Comment by jpmonettas** [comment]
@velios thanks again, appreciate the kind words. Will maybe give it another try!
