### ISSUE TITLE
Latest nrepl 1.2 release breaks FlowStorm 3.15.5 nrepl.middleware functionality

### ISSUE THREAD

**Issue by vedang** [flow-storm/flow-storm-debugger#176]
The latest release of nrepl 1.2 breaks Flowstorm 3.15.5 nrepl.middleware because they've re-written nrepl.bencode implementation from multi-methods to protocols. 

I have explained the issue and submitted the fix to it in PR #175 . I'm creating this issue to help with discovery in the meantime.

**Comment by jpmonettas** [comment]
Oh dang. Thanks for the issue and the PR @vedang. But shouldn't merging that break it for everybody on previous versions of nrepl?

But I think we are lucky, I figured that this extension isn't being used anymore, so if you want to change the PR to just get rid of it I will merge it.

**Comment by vedang** [comment]
Happy to update the PR. I'll do it and push new changes tomorrow.

**Comment by vedang** [comment]
I'm working on this today! Will push the changes in some time.
