### ISSUE TITLE
Put all resources under a flowstorm folder to avoid collisions

### ISSUE THREAD

**Issue by rafd** [flow-storm/flow-storm-debugger#178]
AFAIK, any files under `resources` will collide with similarly named files in users' projects. [[1](https://stackoverflow.com/questions/2982570/should-all-resources-in-a-java-web-application-be-uniquely-named)][[2](https://stackoverflow.com/questions/5292283/use-a-dependencys-resources)]

Ex. `resources/styles.css` (which currently exists in flowstorm), can be accidentally overridden if a user has `resources/styles.css` in their own project (and flowstorm pulled in).

This may result in potential issues with a user using flowstorm (flowstorm files accidentally overridden) or in their own projects (their files overridden by flowstorm ones). 

(This typically isn't an issue with other libraries, because they don't have `resources`, just `src` files).

The simplest solution would be to "namespace" flowstorms resources, ie. move all files under `resources/` to, say, `resources/flow-storm/`.

**Comment by jpmonettas** [comment]
Ohh you are right, I'll namespace all resources
