### ISSUE TITLE
Show binding context for inspected frame

### ISSUE THREAD

**Issue by velios** [flow-storm/flow-storm-debugger#187]
As always thank you for perfect tool. It's helps a lot every day.

I'm pretty often use flowstorm to understand what broke in test after make changes in code. And i need to navigate to some particular testing block. Testing macro add testing-contexts as binding.

```clojure
(defmacro testing
  {:added "1.1"}
  [string & body]
  `(binding [*testing-contexts* (conj *testing-contexts* ~string)]
     ~@body))
```

If i understand it correctly it is theoretically possible to show bindings for current frame in flowstorm. Maybe in same section with Locals/Stack/Bindings or other way.
<img width="326" alt="image" src="https://github.com/user-attachments/assets/7275f9a8-39a3-4cdb-91fb-1178bd543191">

It's also will be cool to have ability of search across captured binding values in the same manner as in Search tool.
But maybe it's really rare need for most users. For now only case i really try to solve is fast navigation to particular testing section.

**Comment by jpmonettas** [comment]
Hi! Glad to hear you find FlowStorm helpful.

I'm not sure I follow, maybe you can expand a little bit more on what you need to see or navigate faster.

One thing that can be useful for understanding code changes is to use multiple flows. You can record a test execution on `flow-0` without the changes for example, then make the code changes (redefine some functions or whatever) and run the test again and record it under `flow-1`. Then you will have the two flows to compare.

![latest-screenshot](https://github.com/user-attachments/assets/246b4a97-2288-42e2-b805-613b1db146ad)
You can see bindings in the Locals tab, which means what name is bound to what value inside a function frame, but that has nothing to do with the `bindings` keyword in Clojure which is about re-binding global dynamic vars for a scope.

> i need to navigate to some particular testing block. Testing macro add testing-contexts as binding

this I'm not sure I follow, can you expand on it? Like why you need adding those strings? If you can expand on the problem maybe there is already something better for it.

**Comment by velios** [comment]
Maybe with video i can add some context

https://github.com/user-attachments/assets/ff3a2453-7bdf-4e33-93a6-4081a6864926

**Comment by jpmonettas** [comment]
Hey, thanks for the video.
So, there is currently nothing being recorded about dynamic bindings context at each point in time.

But if the purpose of that custom testing macro is so given a random point in the recording quickly see what "testing" are you into by looking at the tree, maybe instead of that macro you can define it like :

```clojure
(defmacro testing [string & body]
   `((fn [x#] ~@body) ~string))
```

so when you then use it like : 
```clojure
(deftest my-test
  (testing "Some test 1"
    (is (= 20 (other-function 4 5)))))
```

will then show on the tree like : 
![testing](https://github.com/user-attachments/assets/e8b7c484-c140-4776-bec5-971abecdf425)

And maybe you can go even crazier like : 
```clojure
(defmacro testing [string & body]
  `((fn ~(symbol (clojure.string/replace string " " "_")) [x#]
      ~@body)
    ~string))
```
which you can then see on the stack like : 
![testing2](https://github.com/user-attachments/assets/71db7e16-859a-4451-8e3b-55ded007c0cc)

Does it make sense?

**Comment by velios** [comment]
Amazing and elegant solution to my problem, thank you very much. Also, with a little magic, it's possible to make it work instead of standart clojure.test/testing. Anyway i ran flowstorm with separate profile and can add it here as well. Decided to make separate [flowstorm-testing-extras](https://github.com/velios/flowstorm-testing-extras) repo for this solution. Describe little details in readme. I understand only how to make it work with leiningen.
