### ISSUE TITLE
UX Hierarchy is ambiguous; move vertically oriented left-hand tabs to the main toolbar and orient them horizontally

### ISSUE THREAD

**Issue by matt-y** [flow-storm/flow-storm-debugger#66]
First off: the issue title is prescriptive but I am hoping this is more of a conversation starter about evolving the UX of the tool and not me just waving my hands telling you how it should be. I can only offer my own personal opinion about the usability, and I hope that this feedback is taken as constructive, because I really like the tool! I will try to offer some concrete suggestions for improvements as a jumping off point.

### Ambiguous hierarchy / legibility problems

I am (personally) finding the vertically oriented left-hand tab menu difficult to use for two reasons. First, the vertical text is hard to read. [There are some citations available on actual studies located here in this stack exchange answer that make a compelling argument against vertical orientation of text in general](https://ux.stackexchange.com/a/124562). I definitely cherry-picked these though, haha. I don't feel that vertically oriented text in a side menu like this is appropriate for the top-level menu in the program. Second, it is not immediately clear that the UI is arranged in a hierarchy. The placement of these main navigational widgets makes a hierarchy more difficult to see. For example, whether or not the "Toolbar" in the flow tab is contained within the flow tab is not immediately clear. At first glance, that toolbar appears to be for the whole application. 

I'd like to propose the following as a possible solution to resolving those specific issues:

Translating the left-hand tabs into a "Tabbed Toolbar". A tabbed toolbar is a toolbar at the top of the view that shows different contextual actions for each selected tab. A tabbed toolbar in the context of the debugger listing ["Flow", "Browser", "Taps", "Docs"] would change the contents of the main content area to the respective tab, and also show a view-specific toolbar. The "Flow" toolbar would be different than the "Browser" toolbar because these views have different actions and context. A good example of a tabbed toolbar can be found in Microsoft Office, or Libre Office (shown below). This makes very clear what tab has what actions, while also reinforcing a more conventional vertical hierarchy that could help reinforce what context you're currently in when using the app. 

<img width="538" alt="libre-office-tabbed-toolbar" src="https://user-images.githubusercontent.com/278679/209735985-43641a58-deaa-46f6-b0d2-c0c33ca851e5.png">

This is a screenshot of the LibreOffice tabbed toolbar on a windows computer. Each tab contains actions specific to each tab of the UI. The main area of interaction within LIbreOffice Writer (the document) is not changing when a tab is selected, but that shouldn't be a big leap for developers that use text editors with tabbed file editing - we're probably all very familiar with that sort of thing.

#### There are just too many tabs 

Another difficulty I've had with the current UX is that the hierarchy within the main content area is also sometimes ambiguous. I'll use the "Flow" tab as an extended example because is easy to lose track of what exactly I'm currently looking at with two layers of tabs in the "Flow" context. This could be partially due to the active tab styling not being explicit enough, but having two layers of tabs is just confusing in general. Further, this UI is not scalable for a large number of tabs! 

This could be addressed by taking the top level of tabs and distilling them into a left-hand tree-view menu with a list of "flows" that will grow vertically downward the more "flows" you register.  Different threads associated with a flow could be shown underneath each respective flow in a hierarchical fashion. I am picturing something almost exactly to the VSCode file browser, or neotree. This arrangement would be a lot more flexible for extensions, but it would also be scalable with a scrollbar. Users of debuggers should be familiar with this kind of hierarchical view. 

Adding something like sorting/filtering/searching to the tree-view could then become possible, etc. 

----

Thanks for taking the time to read all this. A few relatively minor UX re-arrangements at the edges like the above suggestions would make the tool more scalable and more flexible while also increasing usability quite a bit.

**Comment by jpmonettas** [comment]
Thanks a lot for your feedback and suggestions @matt-y, I thought about some of them in the past and I agree that the current UI is kind of unique (maybe not in the good way) and doesn't follow any standards.

This next year for me is going to be polishing the tool instead of adding features and UI/UX is going to be a big part of that.

I'll leave this issue open for tracking some of the UI changes and will probably go for some of the stuff you describe there, so thanks again, and happy new year!

**Comment by jpmonettas** [comment]
This doesn't apply anymore as of 3.8.4
