### ISSUE TITLE
Implement qualified function name copy

### ISSUE THREAD

**Issue by jpmonettas** [flow-storm/flow-storm-debugger#69]
Being able to copy the fully-qualified name of a fn when it’s selected anywhere in flow-storm (mostly tree-view/browser/function list). 
I often want to copy the fqn fn name, go back to my editor and do something with it.

**Comment by jpmonettas** [comment]
This shouldn't be hard to implement, but I think better than copy the qualified fn name would be to copy the file and line. That way it is easier to open in any editor.

I don't want to add anything that couples it directly to Emacs,  since one of it values is to be IDE/editor independent.

**Comment by agzam** [comment]
> I don't want to add anything that couples it directly to Emacs

No, of course, it shouldn't be tied to Emacs. I probably should've explained what I meant. If you bind this functionality to an global keybinding within the app, or the standard menu item (which is a completely separate conversation - making a menu for Flowstorm would be nice but might be an overkill at this time). So, if there's a keybinding, the external app (in your case - i3wm, in mine - Hammerspoon or Applescript) can invoke it, get the fully-qualified symbol (and location) from the clipboard, pass it to Emacs and let it open the exact file and line.

**Comment by jpmonettas** [comment]
This has been implemented in bf80b98.

- Ctrl-f copies the current qualified funcion symbol to the clipboard
- Ctrl-Shift-f copies the current function call form
- Right clicking on a tree node now shows "Copy qualified function symbol"
- Right clicking on a tree node now shows "Copy function calling form"

The copying of the calling form will leave you a form you can paste and run on the repl to call the function again with the same parameters
